### ISSUE TITLE
Any plans to choose a software license? (Open source?)

### ISSUE THREAD

**Issue by danbri** [adbrebs/spikingRobots#1]

**Comment by adbrebs** [comment]
Sure, it is open source, use whatever you want :).

**Comment by danbri** [comment]
Thanks, but since opensource licenses come with wildly differing constraints (e.g. around derrivative works) it would be great if you mentioned your choice more explicitly in the README. Entirely your choice but I'd recommend http://www.apache.org/licenses/LICENSE-2.0.

(btw my curiosity here was to see if this might be an interesting tool to generate training datasets for sequence learning algorithms e.g. RNN LSTM to try to predict "what happens next"...)

**Comment by danbri** [comment]
https://github.com/adbrebs/spikingRobots/blob/master/README.md - thanks
