### ISSUE TITLE
Missing Settings.h and Settings.cpp

### ISSUE THREAD

**Issue by Xingtao** [adbrebs/spikingRobots#2]
Hi, I am trying to compile the code, but it seems Settings.h & Settings.cpp are missing. Could you help to guide how to get these two files? Thanks.

**Comment by adbrebs** [comment]
Hi, I have added the two files but I really can not guarantee that the code compiles anymore. In particular I don't remember which library versions I used.

**Comment by Xingtao** [comment]
Use Qwt-6.0.0 with Qt4.8, the code can do the compilation now. Thanks.

**Comment by Xingtao** [comment]
By the way, there are API changes in Qwt library,  so Qwt-5.2 & Qwt-6.1 are not compatible with the code.

**Comment by adbrebs** [comment]
Ok great! So it compiles and the gui works?

**Comment by Xingtao** [comment]
Yes, GUI works well.
